version: "3.8"
services:
  nginx-react:
    container_name: react-redux-boilerplate
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      NODE_ENV: production